"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { checklistTitles, currentMonth, currentYear, demoFirm, demoProfiles, demoTemplates, fillTemplate, makeWaLink, money, monthName, statusLabel, type ChecklistItem, type Client, type GstWorkRecord, type Payment, type Task, type WorkflowStatus } from "@/lib/taxflow";
import { Badge, MetricCard } from "./shared";

type Tab = "Dashboard" | "Clients" | "GST Work" | "Documents" | "Tasks" | "Reminders" | "Payments" | "Calendar" | "Settings";
type Workspace = { clients: Client[]; work: GstWorkRecord[]; payments: Payment[]; tasks: Task[]; docs: ChecklistItem[]; firmName: string };
type Row = { record: GstWorkRecord; client: Client; staff: string; payment?: Payment };
const tabs: Tab[] = ["Dashboard", "Clients", "GST Work", "Documents", "Tasks", "Reminders", "Payments", "Calendar", "Settings"];
const flow: WorkflowStatus[] = ["waiting_for_client", "documents_received", "in_progress", "ready_for_review", "client_approval_pending", "filed", "completed"];
const key = "taxflow_workspace_v3_empty";
const fresh = (): Workspace => ({ clients: [], work: [], payments: [], tasks: [], docs: [], firmName: "My CA Firm" });

export default function WorkspaceApp() {
  const [ws, setWs] = useState<Workspace>(fresh);
  const [ready, setReady] = useState(false);
  const [tab, setTab] = useState<Tab>("Dashboard");
  const [query, setQuery] = useState("");
  const [clientId, setClientId] = useState("");
  const [templateId, setTemplateId] = useState(demoTemplates[0]?.id || "");
  const [sent, setSent] = useState(false);

  useEffect(() => { const raw = localStorage.getItem(key); if (raw) { try { const parsed = JSON.parse(raw) as Workspace; setWs(parsed); setClientId(parsed.clients[0]?.id || ""); } catch { localStorage.removeItem(key); } } setReady(true); }, []);
  useEffect(() => { if (ready) localStorage.setItem(key, JSON.stringify(ws)); }, [ready, ws]);

  const rows = useMemo<Row[]>(() => ws.work.map((record) => { const client = ws.clients.find((c) => c.id === record.client_id); if (!client) return null; return { record, client, staff: demoProfiles.find((p) => p.id === record.assigned_staff_id)?.full_name || "Unassigned", payment: ws.payments.find((p) => p.client_id === record.client_id) }; }).filter((r): r is Row => Boolean(r)), [ws]);
  const filtered = ws.clients.filter((c) => [c.business_name, c.owner_name, c.gstin, c.city].join(" ").toLowerCase().includes(query.toLowerCase()));
  const selected = ws.clients.find((c) => c.id === clientId) || ws.clients[0];
  const selectedWork = selected ? ws.work.find((w) => w.client_id === selected.id) : undefined;
  const template = demoTemplates.find((t) => t.id === templateId) || demoTemplates[0];
  const missing = selected ? ws.docs.filter((d) => d.client_id === selected.id && d.status === "missing").map((d) => d.title).join(", ") || "No missing documents" : "";
  const message = selected && template ? fillTemplate(template.body, { client_name: selected.owner_name, business_name: selected.business_name, month: monthName(selectedWork?.month || currentMonth), year: selectedWork?.year || currentYear, missing_documents: missing, gst_payable_amount: selectedWork?.gst_payable_amount || 0, firm_name: ws.firmName, staff_name: demoProfiles.find((p) => p.id === selected.assigned_staff_id)?.full_name || "Tax team", payment_amount: selected.monthly_fee }) : "Add a client first to generate reminders.";
  const metrics = [["Active clients", ws.clients.filter((c) => c.status === "active").length], ["Pending filings", ws.work.filter((w) => w.filing_status !== "filed").length], ["Waiting docs", ws.work.filter((w) => w.document_status === "missing").length], ["Ready review", ws.work.filter((w) => w.workflow_status === "ready_for_review").length], ["Filed", ws.work.filter((w) => w.filing_status === "filed").length], ["Unpaid", money(ws.payments.filter((p) => p.status !== "paid").reduce((s, p) => s + p.amount_due - p.amount_paid, 0))], ["Overdue tasks", ws.tasks.filter((t) => t.status !== "done" && new Date(t.due_date) < new Date()).length]] as const;

  function addClient(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = new FormData(e.currentTarget); const now = new Date().toISOString(); const id = `client-${Date.now()}`; const fee = Number(data.get("monthly_fee") || 0); const assigned = String(data.get("assigned_staff_id") || "user-staff-1"); const workId = `work-${Date.now()}`; const client: Client = { id, firm_id: demoFirm.id, business_name: String(data.get("business_name") || "New Client"), owner_name: String(data.get("owner_name") || "Owner"), gstin: String(data.get("gstin") || ""), phone: String(data.get("phone") || ""), email: String(data.get("email") || ""), city: String(data.get("city") || ""), business_type: String(data.get("business_type") || ""), gst_frequency: String(data.get("gst_frequency") || "monthly") as Client["gst_frequency"], assigned_staff_id: assigned, monthly_fee: fee, status: String(data.get("status") || "active") as Client["status"], notes: String(data.get("notes") || ""), created_at: now, updated_at: now }; const record: GstWorkRecord = { id: workId, firm_id: demoFirm.id, client_id: id, month: currentMonth, year: currentYear, assigned_staff_id: assigned, workflow_status: "waiting_for_client", document_status: "missing", approval_status: "pending", filing_status: "not_filed", gst_payable_amount: 0, filing_date: null, notes: "", last_followup_at: null, next_followup_at: new Date(currentYear, currentMonth - 1, 20).toISOString(), created_at: now, updated_at: now }; const payment: Payment = { id: `payment-${Date.now()}`, firm_id: demoFirm.id, client_id: id, month: currentMonth, year: currentYear, amount_due: fee, amount_paid: 0, due_date: new Date(currentYear, currentMonth - 1, 25).toISOString(), status: fee > 0 ? "unpaid" : "paid", payment_notes: "" }; const docs = checklistTitles.map((title, i) => ({ id: `${workId}-doc-${i}`, firm_id: demoFirm.id, client_id: id, gst_work_id: workId, title, status: "missing" as const, remarks: "", file_path: null, uploaded_by: null, uploaded_at: null })); setWs((w) => ({ ...w, clients: [client, ...w.clients], work: [record, ...w.work], payments: [payment, ...w.payments], docs: [...docs, ...w.docs] })); setClientId(id); e.currentTarget.reset(); }
  function updateFlow(id: string, status: WorkflowStatus) { setWs((w) => ({ ...w, work: w.work.map((r) => r.id === id ? { ...r, workflow_status: status, document_status: status === "documents_received" ? "received" : r.document_status, filing_status: status === "filed" || status === "completed" ? "filed" : r.filing_status, filing_date: status === "filed" || status === "completed" ? new Date().toISOString() : r.filing_date, updated_at: new Date().toISOString() } : r) })); }
  function updateDoc(id: string, status: ChecklistItem["status"]) { setWs((w) => ({ ...w, docs: w.docs.map((d) => d.id === id ? { ...d, status } : d) })); }
  function paid(id: string) { setWs((w) => ({ ...w, payments: w.payments.map((p) => p.id === id ? { ...p, amount_paid: p.amount_due, status: "paid" } : p) })); }
  function toggleTask(id: string) { setWs((w) => ({ ...w, tasks: w.tasks.map((t) => t.id === id ? { ...t, status: t.status === "done" ? "todo" : "done" } : t) })); }
  function reset() { if (confirm("Reset this browser workspace? This removes your locally saved clients.")) { const next = fresh(); setWs(next); setClientId(""); localStorage.setItem(key, JSON.stringify(next)); } }

  return <main className="min-h-screen bg-slate-50 text-slate-950"><div className="flex min-h-screen"><aside className="hidden w-72 border-r bg-white p-5 lg:block"><div className="rounded-3xl bg-slate-950 p-5 text-white"><p className="text-2xl font-black">TaxFlow</p><p className="text-sm text-slate-300">CA/GST firm control room</p></div><nav className="mt-6 space-y-2">{tabs.map((t) => <button key={t} onClick={() => setTab(t)} className={`w-full rounded-2xl px-4 py-3 text-left font-bold ${tab === t ? "bg-blue-600 text-white" : "hover:bg-slate-100"}`}>{t}</button>)}</nav></aside><section className="flex-1"><header className="sticky top-0 z-10 border-b bg-white/90 p-4 backdrop-blur"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-sm font-bold text-blue-700">{ws.firmName}</p><h1 className="text-2xl font-black">{tab}</h1></div><div className="flex gap-2 overflow-x-auto lg:hidden">{tabs.map((t) => <button key={t} onClick={() => setTab(t)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-bold ${tab === t ? "bg-blue-600 text-white" : "border bg-white"}`}>{t}</button>)}</div><div className="flex gap-2"><a href="/login" className="w-fit rounded-full bg-blue-600 px-4 py-2 text-sm font-bold text-white">Sign in</a><button onClick={reset} className="w-fit rounded-full border bg-white px-4 py-2 text-sm font-bold text-red-700">Reset</button></div></div></header><div className="p-4 lg:p-8">{tab === "Dashboard" && <><div className="mb-4 rounded-3xl border bg-white p-4 text-sm font-semibold text-slate-700">New users start with zero clients. Add your first client from the Clients tab. Data is saved in this browser until cloud auth is fully connected.</div><div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, value]) => <MetricCard key={label} label={label} value={value} />)}</div>{rows.length ? <WorkTable rows={rows} updateFlow={updateFlow} /> : <EmptyStart />}</>}{tab === "Clients" && <Clients clients={filtered} query={query} setQuery={setQuery} addClient={addClient} />}{tab === "GST Work" && (rows.length ? <WorkTable rows={rows} updateFlow={updateFlow} /> : <EmptyStart />)}{tab === "Documents" && <Docs clients={ws.clients} docs={ws.docs} updateDoc={updateDoc} />}{tab === "Tasks" && <Tasks tasks={ws.tasks} toggle={toggleTask} clients={ws.clients} />}{tab === "Reminders" && <Reminders clients={ws.clients} clientId={clientId} setClientId={setClientId} templateId={templateId} setTemplateId={setTemplateId} selected={selected} message={message} sent={sent} setSent={setSent} />}{tab === "Payments" && <Payments payments={ws.payments} paid={paid} clients={ws.clients} />}{tab === "Calendar" && <Calendar work={ws.work} payments={ws.payments} tasks={ws.tasks} clients={ws.clients} />}{tab === "Settings" && <Settings firmName={ws.firmName} setFirmName={(firmName) => setWs((w) => ({ ...w, firmName }))} />}</div></section></div></main>;
}
function EmptyStart(){return <div className="rounded-3xl border border-dashed bg-white p-8 text-center"><h2 className="text-2xl font-black">No clients yet</h2><p className="mt-2 text-slate-500">Go to Clients and add your first GST client. TaxFlow will automatically create GST work, documents and payment tracking.</p></div>}
function WorkTable({ rows, updateFlow }: { rows: Row[]; updateFlow: (id: string, s: WorkflowStatus) => void }) { return <div className="rounded-3xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="text-xl font-black">Monthly GST work</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-slate-50 text-left"><tr>{["Client", "GSTIN", "Staff", "Month", "Docs", "Workflow", "Approval", "Filing", "Fee", "Next"].map((h) => <th key={h} className="p-4 font-black">{h}</th>)}</tr></thead><tbody>{rows.map(({ record, client, staff, payment }) => <tr key={record.id} className="border-t"><td className="p-4 font-bold">{client.business_name}</td><td className="p-4">{client.gstin}</td><td className="p-4">{staff}</td><td className="p-4">{monthName(record.month)} {record.year}</td><td className="p-4"><Badge value={record.document_status} /></td><td className="p-4"><Badge value={record.workflow_status} /></td><td className="p-4"><Badge value={record.approval_status} /></td><td className="p-4"><Badge value={record.filing_status} /></td><td className="p-4"><Badge value={payment?.status || "unpaid"} /></td><td className="p-4"><select className="rounded-xl border px-3 py-2" value={record.workflow_status} onChange={(e) => updateFlow(record.id, e.target.value as WorkflowStatus)}>{flow.map((s) => <option key={s} value={s}>{statusLabel[s]}</option>)}</select></td></tr>)}</tbody></table></div></div>; }
function Clients({ clients, query, setQuery, addClient }: { clients: Client[]; query: string; setQuery: (v: string) => void; addClient: (e: FormEvent<HTMLFormElement>) => void }) { return <div className="grid gap-6 xl:grid-cols-[1fr_360px]"><div><input className="mb-4 w-full rounded-2xl border px-4 py-3" placeholder="Search clients" value={query} onChange={(e) => setQuery(e.target.value)} />{clients.length ? <div className="grid gap-4 md:grid-cols-2">{clients.map((c) => <div key={c.id} className="rounded-3xl border bg-white p-5"><div className="flex justify-between"><h3 className="font-black">{c.business_name}</h3><Badge value={c.status} /></div><p className="text-sm text-slate-500">{c.owner_name} · {c.city}</p><p className="mt-3 text-sm">GSTIN: <b>{c.gstin || "Not added"}</b></p><p className="text-sm">Fee: <b>{money(c.monthly_fee)}</b></p></div>)}</div> : <EmptyStart />}</div><form onSubmit={addClient} className="h-fit rounded-3xl border bg-white p-5"><h2 className="text-xl font-black">Add client</h2>{["business_name", "owner_name", "gstin", "phone", "email", "city", "business_type", "monthly_fee", "notes"].map((f) => <input key={f} name={f} placeholder={f.replace(/_/g, " ")} className="mt-3 w-full rounded-2xl border px-4 py-3" />)}<select name="gst_frequency" className="mt-3 w-full rounded-2xl border px-4 py-3"><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="composition">Composition</option></select><select name="assigned_staff_id" className="mt-3 w-full rounded-2xl border px-4 py-3">{demoProfiles.filter((p) => p.role === "staff").map((p) => <option key={p.id} value={p.id}>{p.full_name}</option>)}</select><button className="mt-4 w-full rounded-2xl bg-blue-600 px-4 py-3 font-black text-white">Create client</button></form></div>; }
function Docs({ clients, docs, updateDoc }: { clients: Client[]; docs: ChecklistItem[]; updateDoc: (id: string, s: ChecklistItem["status"]) => void }) { if(!clients.length)return <EmptyStart/>; return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{clients.map((c) => <div key={c.id} className="rounded-3xl border bg-white p-5"><h3 className="font-black">{c.business_name}</h3>{docs.filter((d) => d.client_id === c.id).map((d) => <div key={d.id} className="mt-2 flex items-center justify-between rounded-2xl bg-slate-50 p-3 text-sm"><span>{d.title}</span><select className="rounded-xl border px-2 py-1" value={d.status} onChange={(e) => updateDoc(d.id, e.target.value as ChecklistItem["status"])}><option value="missing">Missing</option><option value="received">Received</option><option value="checked">Checked</option><option value="issue_found">Issue</option></select></div>)}</div>)}</div>; }
function Tasks({ tasks, toggle, clients }: { tasks: Task[]; toggle: (id: string) => void; clients: Client[] }) { if(!tasks.length)return <div className="rounded-3xl border border-dashed bg-white p-8 text-center"><h2 className="text-2xl font-black">No tasks yet</h2><p className="mt-2 text-slate-500">Task creation will be added next. Client GST work and document tracking are already usable.</p></div>; return <div className="grid gap-4 md:grid-cols-3">{["My tasks", "All tasks", "Overdue"].map((view) => <div key={view} className="rounded-3xl border bg-white p-5"><h2 className="text-xl font-black">{view}</h2>{tasks.filter((t) => view !== "Overdue" || new Date(t.due_date) < new Date()).map((t) => <button key={t.id} onClick={() => toggle(t.id)} className="mt-3 w-full rounded-2xl bg-slate-50 p-4 text-left"><b>{t.title}</b><p className="text-sm text-slate-500">{clients.find((c) => c.id === t.client_id)?.business_name}</p><Badge value={t.status} /></button>)}</div>)}</div>; }
function Reminders({ clients, clientId, setClientId, templateId, setTemplateId, selected, message, sent, setSent }: { clients: Client[]; clientId: string; setClientId: (v: string) => void; templateId: string; setTemplateId: (v: string) => void; selected?: Client; message: string; sent: boolean; setSent: (v: boolean) => void }) { return <div className="rounded-3xl border bg-white p-5"><div className="grid gap-4 md:grid-cols-2"><select className="rounded-2xl border px-4 py-3" value={clientId} onChange={(e) => setClientId(e.target.value)}>{clients.map((c) => <option key={c.id} value={c.id}>{c.business_name}</option>)}</select><select className="rounded-2xl border px-4 py-3" value={templateId} onChange={(e) => setTemplateId(e.target.value)}>{demoTemplates.map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</select></div><textarea className="mt-4 min-h-56 w-full rounded-2xl border p-4" value={message} readOnly /><div className="mt-4 flex gap-3"><a href={selected ? makeWaLink(selected.phone, message) : "#"} target="_blank" rel="noreferrer" className="rounded-2xl bg-green-600 px-5 py-3 font-black text-white">Open WhatsApp</a><button onClick={() => setSent(true)} className="rounded-2xl border px-5 py-3 font-black">Mark sent</button>{sent && <span className="rounded-2xl bg-emerald-50 px-5 py-3 font-black text-emerald-700">Saved</span>}</div></div>; }
function Payments({ payments, paid, clients }: { payments: Payment[]; paid: (id: string) => void; clients: Client[] }) { if(!payments.length)return <EmptyStart/>; return <div className="grid gap-4 md:grid-cols-3">{["Unpaid", "Overdue", "Paid"].map((view) => <div key={view} className="rounded-3xl border bg-white p-5"><h2 className="text-xl font-black">{view}</h2>{payments.filter((p) => view === "Unpaid" ? p.status !== "paid" : view === "Overdue" ? p.status === "overdue" : p.status === "paid").map((p) => <button key={p.id} onClick={() => paid(p.id)} className="mt-3 w-full rounded-2xl bg-slate-50 p-4 text-left"><b>{clients.find((c) => c.id === p.client_id)?.business_name}</b><p className="text-sm">Due {money(p.amount_due)} · Paid {money(p.amount_paid)}</p><Badge value={p.status} /></button>)}</div>)}</div>; }
function Calendar({ work, payments, tasks, clients }: { work: GstWorkRecord[]; payments: Payment[]; tasks: Task[]; clients: Client[] }) { const events = [...work.map((w) => ({ d: w.next_followup_at || w.created_at, t: `GST follow-up: ${clients.find((c) => c.id === w.client_id)?.business_name || "Client"}` })), ...payments.map((p) => ({ d: p.due_date, t: `Fee due: ${clients.find((c) => c.id === p.client_id)?.business_name || "Client"}` })), ...tasks.map((t) => ({ d: t.due_date, t: `Task: ${t.title}` }))].sort((a, b) => +new Date(a.d) - +new Date(b.d)); if(!events.length)return <EmptyStart/>; return <div className="rounded-3xl border bg-white p-5"><h2 className="text-xl font-black">Compliance calendar</h2>{events.map((e, i) => <div key={i} className="flex gap-4 border-b py-4"><b className="w-32">{new Date(e.d).toLocaleDateString("en-IN")}</b><span>{e.t}</span></div>)}</div>; }
function Settings({ firmName, setFirmName }: { firmName: string; setFirmName: (v: string) => void }) { return <div className="rounded-3xl border bg-white p-5"><h2 className="text-xl font-black">Firm settings</h2><input className="mt-4 w-full rounded-2xl border px-4 py-3" value={firmName} onChange={(e) => setFirmName(e.target.value)} /><p className="mt-3 text-sm text-slate-500">Default GST due day: 20. Default fee due day: 25. Email/Google login UI is at /login.</p></div>; }
