"use client";

import { FormEvent, useMemo, useState } from "react";
import { demoChecklistItems, demoClients, demoFirm, demoPayments, demoProfiles, demoTasks, demoTemplates, demoWorkRecords, fillTemplate, makeWaLink, money, monthName, statusLabel, type Client, type GstWorkRecord, type Payment, type Task, type WorkflowStatus } from "@/lib/taxflow";

type Tab = "Dashboard" | "Clients" | "GST Work" | "Documents" | "Tasks" | "Reminders" | "Payments" | "Calendar" | "Settings";
type Row = { record: GstWorkRecord; client: Client; staff: string; payment?: Payment };
const tabs: Tab[] = ["Dashboard", "Clients", "GST Work", "Documents", "Tasks", "Reminders", "Payments", "Calendar", "Settings"];
const flow: WorkflowStatus[] = ["documents_received", "in_progress", "ready_for_review", "client_approval_pending", "filed", "completed"];

export default function Home() {
  const [tab, setTab] = useState<Tab>("Dashboard");
  const [clients, setClients] = useState<Client[]>(demoClients);
  const [work, setWork] = useState<GstWorkRecord[]>(demoWorkRecords);
  const [payments, setPayments] = useState<Payment[]>(demoPayments);
  const [tasks, setTasks] = useState<Task[]>(demoTasks);
  const [query, setQuery] = useState("");
  const [selectedClientId, setSelectedClientId] = useState(demoClients[0]?.id || "");
  const [selectedTemplateId, setSelectedTemplateId] = useState(demoTemplates[0]?.id || "");
  const [firmName, setFirmName] = useState(demoFirm.name);
  const [saved, setSaved] = useState(false);

  const rows = useMemo<Row[]>(() => work.map((record) => {
    const client = clients.find((item) => item.id === record.client_id) || clients[0];
    return { record, client, staff: demoProfiles.find((p) => p.id === record.assigned_staff_id)?.full_name || "Unassigned", payment: payments.find((p) => p.client_id === record.client_id) };
  }).filter((item) => item.client), [clients, payments, work]);

  const selectedClient = clients.find((client) => client.id === selectedClientId) || clients[0];
  const selectedWork = work.find((record) => record.client_id === selectedClient?.id) || work[0];
  const selectedTemplate = demoTemplates.find((template) => template.id === selectedTemplateId) || demoTemplates[0];
  const missingDocs = demoChecklistItems.filter((doc) => doc.client_id === selectedClient?.id && doc.status === "missing").map((doc) => doc.title).join(", ") || "No missing documents";
  const message = selectedClient && selectedTemplate ? fillTemplate(selectedTemplate.body, { client_name: selectedClient.owner_name, business_name: selectedClient.business_name, month: monthName(selectedWork.month), year: selectedWork.year, missing_documents: missingDocs, gst_payable_amount: selectedWork.gst_payable_amount, firm_name: firmName, staff_name: demoProfiles.find((profile) => profile.id === selectedClient.assigned_staff_id)?.full_name || "Tax team", payment_amount: selectedClient.monthly_fee }) : "";

  const metrics = [
    ["Active clients", clients.filter((c) => c.status === "active").length],
    ["Pending filings", work.filter((w) => w.filing_status !== "filed").length],
    ["Waiting docs", work.filter((w) => w.document_status === "missing").length],
    ["Ready review", work.filter((w) => w.workflow_status === "ready_for_review").length],
    ["Filed", work.filter((w) => w.filing_status === "filed").length],
    ["Unpaid", money(payments.filter((p) => p.status !== "paid").reduce((sum, p) => sum + p.amount_due - p.amount_paid, 0))],
    ["Overdue tasks", tasks.filter((t) => t.status !== "done" && new Date(t.due_date) < new Date()).length]
  ] as const;

  function updateWorkflow(id: string, status: WorkflowStatus) {
    setWork((items) => items.map((item) => item.id === id ? { ...item, workflow_status: status, document_status: status === "documents_received" ? "received" : item.document_status, filing_status: status === "filed" || status === "completed" ? "filed" : item.filing_status, filing_date: status === "filed" || status === "completed" ? new Date().toISOString() : item.filing_date, updated_at: new Date().toISOString() } : item));
  }

  function addClient(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const now = new Date().toISOString();
    const client: Client = { id: `client-${Date.now()}`, firm_id: demoFirm.id, business_name: String(data.get("business_name") || "New Client"), owner_name: String(data.get("owner_name") || "Owner"), gstin: String(data.get("gstin") || "36AAAAA0000A1Z5"), phone: String(data.get("phone") || "919999999999"), email: String(data.get("email") || "client@example.com"), city: String(data.get("city") || "Hyderabad"), business_type: String(data.get("business_type") || "Business"), gst_frequency: "monthly", assigned_staff_id: String(data.get("assigned_staff_id") || "user-staff-1"), monthly_fee: Number(data.get("monthly_fee") || 0), status: "active", notes: String(data.get("notes") || ""), created_at: now, updated_at: now };
    setClients((items) => [client, ...items]);
    event.currentTarget.reset();
  }

  return <main className="min-h-screen bg-slate-50 text-slate-950"><div className="flex min-h-screen"><aside className="hidden w-72 border-r bg-white p-5 lg:block"><div className="rounded-3xl bg-slate-950 p-5 text-white"><p className="text-2xl font-black">TaxFlow</p><p className="text-sm text-slate-300">CA/GST firm control room</p></div><nav className="mt-6 space-y-2">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`w-full rounded-2xl px-4 py-3 text-left font-bold ${tab === item ? "bg-blue-600 text-white" : "hover:bg-slate-100"}`}>{item}</button>)}</nav></aside><section className="flex-1"><header className="sticky top-0 z-10 border-b bg-white/90 p-4 backdrop-blur"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-sm font-bold text-blue-700">{firmName}</p><h1 className="text-2xl font-black">{tab}</h1></div><div className="flex gap-2 overflow-x-auto lg:hidden">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-bold ${tab === item ? "bg-blue-600 text-white" : "border bg-white"}`}>{item}</button>)}</div><span className="w-fit rounded-full border bg-white px-4 py-2 text-sm font-bold">Demo-ready MVP</span></div></header><div className="p-4 lg:p-8">{tab === "Dashboard" && <><div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, value]) => <Card key={label} label={label} value={value} />)}</div><WorkTable rows={rows} updateWorkflow={updateWorkflow} /></>}{tab === "Clients" && <ClientsPanel clients={clients} query={query} setQuery={setQuery} addClient={addClient} />}{tab === "GST Work" && <WorkTable rows={rows} updateWorkflow={updateWorkflow} />}{tab === "Documents" && <DocumentsPanel clients={clients} />}{tab === "Tasks" && <TasksPanel tasks={tasks} setTasks={setTasks} clients={clients} />}{tab === "Reminders" && <RemindersPanel clients={clients} selectedClientId={selectedClientId} setSelectedClientId={setSelectedClientId} selectedTemplateId={selectedTemplateId} setSelectedTemplateId={setSelectedTemplateId} selectedClient={selectedClient} message={message} saved={saved} setSaved={setSaved} />}{tab === "Payments" && <PaymentsPanel payments={payments} setPayments={setPayments} clients={clients} />}{tab === "Calendar" && <CalendarPanel work={work} payments={payments} tasks={tasks} clients={clients} />}{tab === "Settings" && <SettingsPanel firmName={firmName} setFirmName={setFirmName} />}</div></section></div></main>;
}

function Badge({ value }: { value: string }) { const bad = ["missing", "overdue", "risky", "urgent", "blocked", "issue_found"].some((x) => value.includes(x)); const good = ["paid", "filed", "completed", "checked", "approved"].some((x) => value.includes(x)); return <span className={`inline-flex rounded-full px-3 py-1 text-xs font-black ${bad ? "bg-red-50 text-red-700" : good ? "bg-emerald-50 text-emerald-700" : "bg-blue-50 text-blue-700"}`}>{statusLabel[value] || value}</span>; }
function Card({ label, value }: { label: string; value: string | number }) { return <div className="rounded-3xl border bg-white p-5 shadow-sm"><p className="text-sm font-bold text-slate-500">{label}</p><p className="mt-3 text-3xl font-black">{value}</p></div>; }
function WorkTable({ rows, updateWorkflow }: { rows: Row[]; updateWorkflow: (id: string, status: WorkflowStatus) => void }) { return <div className="rounded-3xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="text-xl font-black">Monthly GST work table</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-sm"><thead className="bg-slate-50 text-left"><tr>{["Client", "GSTIN", "Staff", "Month", "Documents", "Workflow", "Approval", "Filing", "Fee", "Next action"].map((h) => <th key={h} className="p-4 font-black">{h}</th>)}</tr></thead><tbody>{rows.map(({ record, client, staff, payment }) => <tr key={record.id} className="border-t"><td className="p-4 font-bold">{client.business_name}</td><td className="p-4">{client.gstin}</td><td className="p-4">{staff}</td><td className="p-4">{monthName(record.month)} {record.year}</td><td className="p-4"><Badge value={record.document_status} /></td><td className="p-4"><Badge value={record.workflow_status} /></td><td className="p-4"><Badge value={record.approval_status} /></td><td className="p-4"><Badge value={record.filing_status} /></td><td className="p-4"><Badge value={payment?.status || "unpaid"} /></td><td className="p-4"><select className="rounded-xl border px-3 py-2" value={record.workflow_status} onChange={(event) => updateWorkflow(record.id, event.target.value as WorkflowStatus)}>{flow.map((s) => <option key={s} value={s}>{statusLabel[s]}</option>)}</select></td></tr>)}</tbody></table></div></div>; }
function ClientsPanel({ clients, query, setQuery, addClient }: { clients: Client[]; query: string; setQuery: (v: string) => void; addClient: (e: FormEvent<HTMLFormElement>) => void }) { const list = clients.filter((c) => [c.business_name, c.owner_name, c.gstin, c.city].join(" ").toLowerCase().includes(query.toLowerCase())); return <div className="grid gap-6 xl:grid-cols-[1fr_360px]"><div><input className="mb-4 w-full rounded-2xl border px-4 py-3" placeholder="Search clients" value={query} onChange={(e) => setQuery(e.target.value)} /><div className="grid gap-4 md:grid-cols-2">{list.map((c) => <div key={c.id} className="rounded-3xl border bg-white p-5"><div className="flex justify-between"><h3 className="font-black">{c.business_name}</h3><Badge value={c.status} /></div><p className="text-sm text-slate-500">{c.owner_name} · {c.city}</p><p className="mt-3 text-sm">GSTIN: <b>{c.gstin}</b></p><p className="text-sm">Fee: <b>{money(c.monthly_fee)}</b></p></div>)}</div></div><form onSubmit={addClient} className="h-fit rounded-3xl border bg-white p-5"><h2 className="text-xl font-black">Add client</h2>{["business_name", "owner_name", "gstin", "phone", "email", "city", "business_type", "monthly_fee", "notes"].map((f) => <input key={f} name={f} placeholder={f.replace(/_/g, " ")} className="mt-3 w-full rounded-2xl border px-4 py-3" />)}<select name="assigned_staff_id" className="mt-3 w-full rounded-2xl border px-4 py-3">{demoProfiles.filter((p) => p.role === "staff").map((p) => <option key={p.id} value={p.id}>{p.full_name}</option>)}</select><button className="mt-4 w-full rounded-2xl bg-blue-600 px-4 py-3 font-black text-white">Create client</button></form></div>; }
function DocumentsPanel({ clients }: { clients: Client[] }) { return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{demoWorkRecords.map((w) => <div key={w.id} className="rounded-3xl border bg-white p-5"><h3 className="font-black">{clients.find((c) => c.id === w.client_id)?.business_name || "Client"}</h3>{demoChecklistItems.filter((d) => d.gst_work_id === w.id).map((d) => <div key={d.id} className="mt-2 flex justify-between rounded-2xl bg-slate-50 p-3 text-sm"><span>{d.title}</span><Badge value={d.status} /></div>)}</div>)}</div>; }
function TasksPanel({ tasks, setTasks, clients }: { tasks: Task[]; setTasks: (fn: (t: Task[]) => Task[]) => void; clients: Client[] }) { return <div className="grid gap-4 md:grid-cols-3">{["My tasks", "All firm tasks", "Overdue tasks"].map((view) => <div key={view} className="rounded-3xl border bg-white p-5"><h2 className="text-xl font-black">{view}</h2>{tasks.filter((t) => view !== "Overdue tasks" || new Date(t.due_date) < new Date()).map((t) => <button key={t.id} onClick={() => setTasks((items) => items.map((i) => i.id === t.id ? { ...i, status: i.status === "done" ? "todo" : "done" } : i))} className="mt-3 w-full rounded-2xl bg-slate-50 p-4 text-left"><b>{t.title}</b><p className="text-sm text-slate-500">{clients.find((c) => c.id === t.client_id)?.business_name}</p><Badge value={t.status} /></button>)}</div>)}</div>; }
function RemindersPanel({ clients, selectedClientId, setSelectedClientId, selectedTemplateId, setSelectedTemplateId, selectedClient, message, saved, setSaved }: { clients: Client[]; selectedClientId: string; setSelectedClientId: (v: string) => void; selectedTemplateId: string; setSelectedTemplateId: (v: string) => void; selectedClient?: Client; message: string; saved: boolean; setSaved: (v: boolean) => void }) { return <div className="rounded-3xl border bg-white p-5"><div className="grid gap-4 md:grid-cols-2"><select className="rounded-2xl border px-4 py-3" value={selectedClientId} onChange={(e) => setSelectedClientId(e.target.value)}>{clients.map((c) => <option key={c.id} value={c.id}>{c.business_name}</option>)}</select><select className="rounded-2xl border px-4 py-3" value={selectedTemplateId} onChange={(e) => setSelectedTemplateId(e.target.value)}>{demoTemplates.map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</select></div><textarea className="mt-4 min-h-56 w-full rounded-2xl border p-4" value={message} readOnly /><div className="mt-4 flex flex-wrap gap-3"><a href={makeWaLink(selectedClient?.phone || "", message)} target="_blank" rel="noreferrer" className="rounded-2xl bg-green-600 px-5 py-3 font-black text-white">Open in WhatsApp</a><button onClick={() => { setSaved(true); setTimeout(() => setSaved(false), 1800); }} className="rounded-2xl border px-5 py-3 font-black">Mark as sent</button>{saved && <span className="rounded-2xl bg-emerald-50 px-5 py-3 font-black text-emerald-700">Saved</span>}</div></div>; }
function PaymentsPanel({ payments, setPayments, clients }: { payments: Payment[]; setPayments: (fn: (p: Payment[]) => Payment[]) => void; clients: Client[] }) { return <div className="grid gap-4 md:grid-cols-3">{["Unpaid clients", "Overdue fees", "Paid this month"].map((view) => <div key={view} className="rounded-3xl border bg-white p-5"><h2 className="text-xl font-black">{view}</h2>{payments.filter((p) => view === "Unpaid clients" ? p.status !== "paid" : view === "Overdue fees" ? p.status === "overdue" : p.status === "paid").map((p) => <button key={p.id} onClick={() => setPayments((items) => items.map((i) => i.id === p.id ? { ...i, amount_paid: i.amount_due, status: "paid" } : i))} className="mt-3 w-full rounded-2xl bg-slate-50 p-4 text-left"><b>{clients.find((c) => c.id === p.client_id)?.business_name}</b><p className="text-sm">Due {money(p.amount_due)} · Paid {money(p.amount_paid)}</p><Badge value={p.status} /></button>)}</div>)}</div>; }
function CalendarPanel({ work, payments, tasks, clients }: { work: GstWorkRecord[]; payments: Payment[]; tasks: Task[]; clients: Client[] }) { const events = [...work.map((w) => ({ d: w.next_followup_at || w.created_at, t: `GST follow-up: ${clients.find((c) => c.id === w.client_id)?.business_name || "Client"}` })), ...payments.map((p) => ({ d: p.due_date, t: `Fee due: ${clients.find((c) => c.id === p.client_id)?.business_name || "Client"}` })), ...tasks.map((t) => ({ d: t.due_date, t: `Task: ${t.title}` }))].sort((a, b) => +new Date(a.d) - +new Date(b.d)); return <div className="rounded-3xl border bg-white p-5"><h2 className="text-xl font-black">Compliance calendar</h2>{events.map((e, i) => <div key={i} className="flex gap-4 border-b py-4"><b className="w-32">{new Date(e.d).toLocaleDateString("en-IN")}</b><span>{e.t}</span></div>)}</div>; }
function SettingsPanel({ firmName, setFirmName }: { firmName: string; setFirmName: (v: string) => void }) { return <div className="grid gap-6 xl:grid-cols-2"><div className="rounded-3xl border bg-white p-5"><h2 className="text-xl font-black">Firm settings</h2><input className="mt-4 w-full rounded-2xl border px-4 py-3" value={firmName} onChange={(e) => setFirmName(e.target.value)} /><input className="mt-3 w-full rounded-2xl border px-4 py-3" defaultValue={demoFirm.address} /><p className="mt-3 text-sm text-slate-500">Default GST due day: 20. Default fee due day: 25.</p></div><div className="rounded-3xl border bg-white p-5"><h2 className="text-xl font-black">User management</h2>{demoProfiles.map((p) => <div key={p.id} className="mt-3 flex justify-between rounded-2xl bg-slate-50 p-4"><div><b>{p.full_name}</b><p className="text-sm text-slate-500">{p.email}</p></div><Badge value={p.role} /></div>)}</div></div>; }
