export type StatusValue = "Request Received"|"Under Review"|"Documents Required"|"Payment Pending"|"Processing"|"Applied"|"Certificate Ready"|"Delivered"|"Issue"|"Rejected";
export type PaperFixRequest={id?:string;token:string;full_name:string;phone:string;certificate_type:string;district:string;mandal:string;request_type:string;application_number?:string|null;urgency:string;documents_ready:string;notes?:string|null;consent_accepted:boolean;status:StatusValue;status_message?:string|null;internal_note?:string|null;created_at?:string;updated_at?:string};
export type RequestPayload=Omit<PaperFixRequest,"id"|"token"|"status"|"status_message"|"internal_note"|"created_at"|"updated_at">;
export const certificateTypes=["Birth certificate","Caste certificate","Income certificate","Residence certificate","Death certificate","Application tracking","Other certificate work"];
export const statuses:StatusValue[]=["Request Received","Under Review","Documents Required","Payment Pending","Processing","Applied","Certificate Ready","Delivered","Issue","Rejected"];
export const disclaimer="PaperFix is an independent support service, not a government office. Certificate approval depends on official verification and correct documents. Government fee, if any, is separate from PaperFix support charges.";
export const messages:Record<StatusValue,string>={"Request Received":"Your request has been received. Our team will check it shortly.","Under Review":"Your request is under review. Our team is checking the details.","Documents Required":"Some documents or details are required. Our team will message you on WhatsApp.","Payment Pending":"Payment details will be shared after checking your request.","Processing":"Your request is being processed.","Applied":"Your application has been submitted. We will continue tracking it.","Certificate Ready":"Your certificate is ready. Our team will help with digital delivery.","Delivered":"Your certificate delivery support is completed.","Issue":"There is an issue with your request. Our team will contact you on WhatsApp.","Rejected":"The request could not be completed. Approval depends on official verification and correct documents."};
export function isPhone(phone:string){return /^(\+91)?[6-9]\d{9}$/.test(phone.trim().replace(/\s/g,""));}
export function normalizePhone(phone:string){const d=phone.replace(/\D/g,"");return d.length===10?`91${d}`:d;}
export function formatDate(value?:string){return value?new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"Not available";}
export function badge(status:string){if(status==="Delivered")return"bg-emerald-100 text-emerald-800";if(["Certificate Ready","Applied"].includes(status))return"bg-blue-100 text-blue-800";if(["Processing","Under Review"].includes(status))return"bg-amber-100 text-amber-800";if(["Documents Required","Payment Pending"].includes(status))return"bg-orange-100 text-orange-800";if(["Issue","Rejected"].includes(status))return"bg-red-100 text-red-800";return"bg-slate-100 text-slate-800";}
export function whatsapp(r:PaperFixRequest){const msg=`New PaperFix Request\n\nToken: ${r.token}\nName: ${r.full_name}\nPhone: ${r.phone}\nCertificate: ${r.certificate_type}\nDistrict: ${r.district}\nMandal: ${r.mandal}\nRequest Type: ${r.request_type}\nApplication Number: ${r.application_number||"Not provided"}\nUrgency: ${r.urgency}\nDocuments Ready: ${r.documents_ready}\nNotes: ${r.notes||"Not provided"}\n\nCustomer has accepted PaperFix independent service disclaimer.`;return`https://wa.me/919666989331?text=${encodeURIComponent(msg)}`;}
export function customerWa(phone:string,token:string){return`https://wa.me/${normalizePhone(phone)}?text=${encodeURIComponent(`Hi, this is PaperFix regarding your request ${token}.`)}`;}
