"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Client={id:string;business:string;owner:string;gstin:string;phone:string;city:string;fee:number;staff:string};
type Work={id:string;clientId:string;month:string;docs:string;flow:string;approval:string;filing:string;fee:string;payable:number;lastFollowup:string};
const KEY="taxflow_ops_v1";
const docList=["Sales invoices","Purchase invoices","Bank statement","Expense bills","E-way bills","TDS details","Other supporting documents"];
const steps=["waiting_for_client","documents_received","in_progress","ready_for_review","approval_pending","filed","completed"];

export default function Dashboard(){
 const [clients,setClients]=useState<Client[]>([]); const [work,setWork]=useState<Work[]>([]); const [firm,setFirm]=useState("My CA Firm"); const [tab,setTab]=useState("Dashboard"); const [selected,setSelected]=useState("");
 useEffect(()=>{const raw=localStorage.getItem(KEY); if(!raw)return; try{const d=JSON.parse(raw); setClients(d.clients||[]); setWork(d.work||[]); setFirm(d.firm||"My CA Firm"); setSelected(d.clients?.[0]?.id||"")}catch{localStorage.removeItem(KEY)}},[]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({firm,clients,work}))},[firm,clients,work]);
 const rows=useMemo(()=>work.map(w=>({w,c:clients.find(c=>c.id===w.clientId)})).filter(x=>x.c),[work,clients]);
 const client=clients.find(c=>c.id===selected)||clients[0]; const cw=client?work.find(w=>w.clientId===client.id):undefined;
 const missing=docList.join(", "); const reminder=client?`Hi ${client.owner||client.business}, this is ${firm}. For ${cw?.month||"this month"} GST filing, please share: ${missing}.` : "Add a client first.";
 const unpaid=rows.filter(r=>r.w.fee!=="paid").reduce((s,r)=>s+(r.c?.fee||0),0);
 function addClient(e:FormEvent<HTMLFormElement>){e.preventDefault(); const f=new FormData(e.currentTarget); const id="c"+Date.now(); const fee=Number(f.get("fee")||0); const c:Client={id,business:String(f.get("business")||"New client"),owner:String(f.get("owner")||""),gstin:String(f.get("gstin")||""),phone:String(f.get("phone")||""),city:String(f.get("city")||""),fee,staff:String(f.get("staff")||"Unassigned")}; const w:Work={id:"w"+Date.now(),clientId:id,month:new Date().toLocaleString("en-IN",{month:"long",year:"numeric"}),docs:"missing",flow:"waiting_for_client",approval:"pending",filing:"not_filed",fee:fee>0?"unpaid":"paid",payable:0,lastFollowup:""}; setClients(x=>[c,...x]); setWork(x=>[w,...x]); setSelected(id); e.currentTarget.reset()}
 function upd(id:string,k:keyof Work,v:string){setWork(a=>a.map(w=>w.id===id?{...w,[k]:v,lastFollowup:k==="flow"?new Date().toISOString():w.lastFollowup}:w))}
 function reset(){if(confirm("Clear all TaxFlow data saved in this browser?")){setClients([]);setWork([]);setSelected("");localStorage.removeItem(KEY)}}
 return <main className="min-h-screen bg-slate-50 text-slate-950"><div className="flex min-h-screen"><aside className="hidden w-72 border-r bg-white p-5 lg:block"><h1 className="text-3xl font-black">TaxFlow</h1><p className="mt-1 text-sm text-slate-500">GST operations dashboard</p>{["Dashboard","Clients","GST Work","Documents","Reminders","Payments","Settings"].map(t=><button key={t} onClick={()=>setTab(t)} className={`mt-3 w-full rounded-2xl px-4 py-3 text-left font-bold ${tab===t?"bg-blue-600 text-white":"bg-slate-50"}`}>{t}</button>)}</aside><section className="flex-1"><header className="sticky top-0 z-10 border-b bg-white/90 p-4"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p className="text-sm font-bold text-blue-700">{firm}</p><h2 className="text-2xl font-black">{tab}</h2></div><div className="flex gap-2 overflow-x-auto lg:hidden">{["Dashboard","Clients","GST Work","Documents","Reminders","Payments","Settings"].map(t=><button key={t} onClick={()=>setTab(t)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-bold ${tab===t?"bg-blue-600 text-white":"border bg-white"}`}>{t}</button>)}</div><button onClick={reset} className="w-fit rounded-full border bg-white px-4 py-2 text-sm font-bold text-red-700">Reset</button></div></header><div className="p-4 md:p-8">{tab==="Dashboard"&&<><div className="mb-6 grid gap-4 md:grid-cols-4"><Metric t="Clients" v={clients.length}/><Metric t="Pending filings" v={rows.filter(r=>r.w.filing!=="filed").length}/><Metric t="Waiting docs" v={rows.filter(r=>r.w.docs==="missing").length}/><Metric t="Unpaid fees" v={`₹${unpaid.toLocaleString("en-IN")}`}/></div><Work rows={rows} upd={upd}/></>}{tab==="Clients"&&<Clients clients={clients} addClient={addClient}/>} {tab==="GST Work"&&<Work rows={rows} upd={upd}/>} {tab==="Documents"&&<Documents rows={rows} upd={upd}/>} {tab==="Reminders"&&<Reminders clients={clients} selected={selected} setSelected={setSelected} reminder={reminder} client={client}/>} {tab==="Payments"&&<Payments rows={rows} upd={upd}/>} {tab==="Settings"&&<Settings firm={firm} setFirm={setFirm}/>}</div></section></div></main>}
function Metric({t,v}:{t:string;v:string|number}){return <div className="rounded-3xl border bg-white p-5"><p className="text-sm font-bold text-slate-500">{t}</p><p className="mt-2 text-3xl font-black">{v}</p></div>}
function Empty(){return <div className="rounded-3xl border border-dashed bg-white p-8 text-center"><h3 className="text-2xl font-black">No clients yet</h3><p className="mt-2 text-slate-500">Add your first client from the Clients tab.</p></div>}
function Badge({x}:{x:string}){const bad=["missing","unpaid","not_filed","waiting_for_client"].includes(x);const good=["filed","paid","completed","checked","documents_received"].includes(x);return <span className={`rounded-full px-3 py-1 text-xs font-black ${bad?"bg-red-50 text-red-700":good?"bg-emerald-50 text-emerald-700":"bg-blue-50 text-blue-700"}`}>{x.replaceAll("_"," ")}</span>}
function Clients({clients,addClient}:{clients:Client[];addClient:(e:FormEvent<HTMLFormElement>)=>void}){return <div className="grid gap-6 xl:grid-cols-[1fr_360px]"><div>{clients.length? <div className="grid gap-4 md:grid-cols-2">{clients.map(c=><div key={c.id} className="rounded-3xl border bg-white p-5"><h3 className="font-black">{c.business}</h3><p className="text-sm text-slate-500">{c.owner||"Owner"} · {c.city||"City"}</p><p className="mt-3 text-sm">GSTIN: <b>{c.gstin||"Not added"}</b></p><p>Fee: ₹{c.fee.toLocaleString("en-IN")}</p></div>)}</div>:<Empty/>}</div><form onSubmit={addClient} className="rounded-3xl border bg-white p-5"><h3 className="text-xl font-black">Add client</h3>{[["business","Business name"],["owner","Owner name"],["gstin","GSTIN"],["phone","WhatsApp phone"],["city","City"],["staff","Assigned staff"],["fee","Monthly fee"]].map(([n,l])=><input key={n} name={n} placeholder={l} className="mt-3 w-full rounded-2xl border px-4 py-3"/>)}<button className="mt-4 w-full rounded-2xl bg-blue-600 px-4 py-3 font-black text-white">Create client</button></form></div>}
function Work({rows,upd}:{rows:{w:Work;c?:Client}[];upd:(id:string,k:keyof Work,v:string)=>void}){if(!rows.length)return <Empty/>;return <div className="overflow-x-auto rounded-3xl border bg-white"><table className="w-full min-w-[950px] text-sm"><thead className="bg-slate-100 text-left"><tr>{["Client","Month","Docs","Workflow","Approval","Filing","Fee"].map(h=><th key={h} className="p-4 font-black">{h}</th>)}</tr></thead><tbody>{rows.map(({w,c})=><tr key={w.id} className="border-t"><td className="p-4 font-bold">{c?.business}</td><td className="p-4">{w.month}</td><td className="p-4"><select value={w.docs} onChange={e=>upd(w.id,"docs",e.target.value)} className="rounded-xl border px-3 py-2"><option value="missing">Missing</option><option value="received">Received</option><option value="checked">Checked</option><option value="issue_found">Issue found</option></select></td><td className="p-4"><select value={w.flow} onChange={e=>upd(w.id,"flow",e.target.value)} className="rounded-xl border px-3 py-2">{steps.map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></td><td className="p-4"><Badge x={w.approval}/></td><td className="p-4"><Badge x={w.filing}/></td><td className="p-4"><Badge x={w.fee}/></td></tr>)}</tbody></table></div>}
function Documents({rows,upd}:{rows:{w:Work;c?:Client}[];upd:(id:string,k:keyof Work,v:string)=>void}){if(!rows.length)return <Empty/>;return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rows.map(({w,c})=><div key={w.id} className="rounded-3xl border bg-white p-5"><h3 className="font-black">{c?.business}</h3>{docList.map(d=><div key={d} className="mt-2 flex justify-between rounded-2xl bg-slate-50 p-3 text-sm"><span>{d}</span><Badge x={w.docs}/></div>)}</div>)}</div>}
function Reminders({clients,selected,setSelected,reminder,client}:{clients:Client[];selected:string;setSelected:(v:string)=>void;reminder:string;client?:Client}){return <div className="rounded-3xl border bg-white p-5"><select value={selected} onChange={e=>setSelected(e.target.value)} className="w-full rounded-2xl border px-4 py-3">{clients.map(c=><option key={c.id} value={c.id}>{c.business}</option>)}</select><textarea value={reminder} readOnly className="mt-4 min-h-44 w-full rounded-2xl border p-4"/><a className="mt-4 inline-block rounded-2xl bg-green-600 px-5 py-3 font-black text-white" target="_blank" rel="noreferrer" href={client?`https://wa.me/${client.phone.replace(/[^0-9]/g,"")}?text=${encodeURIComponent(reminder)}`:"#"}>Open WhatsApp</a></div>}
function Payments({rows,upd}:{rows:{w:Work;c?:Client}[];upd:(id:string,k:keyof Work,v:string)=>void}){if(!rows.length)return <Empty/>;return <div className="grid gap-4 md:grid-cols-2">{rows.map(({w,c})=><button key={w.id} onClick={()=>upd(w.id,"fee",w.fee==="paid"?"unpaid":"paid")} className="rounded-3xl border bg-white p-5 text-left"><h3 className="font-black">{c?.business}</h3><p>Monthly fee: ₹{(c?.fee||0).toLocaleString("en-IN")}</p><Badge x={w.fee}/></button>)}</div>}
function Settings({firm,setFirm}:{firm:string;setFirm:(v:string)=>void}){return <div className="rounded-3xl border bg-white p-5"><h3 className="text-xl font-black">Firm settings</h3><input value={firm} onChange={e=>setFirm(e.target.value)} className="mt-4 w-full rounded-2xl border px-4 py-3"/></div>}
